-- DDL

CREATE TABLE COURSE
(
    ID   SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE USERS
(
    ID         SERIAL PRIMARY KEY NOT NULL,
    ROLE       VARCHAR(10),
    FIRSTNAME  VARCHAR(25),
    LASTNAME   VARCHAR(25),
    EMAIL      VARCHAR(255),
    PASSWORD   VARCHAR(255),
    COURSE     INTEGER,
    ASSESSMENT INTEGER,
    REVIEW     VARCHAR(255),
    CONSTRAINT FK_COURSENO FOREIGN KEY (COURSE) REFERENCES COURSE (ID)
);

COMMIT;